- 👋 Hi, I’m @omargamer-99
- 👀 I’m interested in anything tech related ...
- 🌱 I’m currently learning front end ...
- 💞️ I’m looking to collaborate on anything really...
- 📫 How to reach me omargamer-99 on X, umargarba7499@gmail.com...
- 😄 Pronouns: He/Him ...
- ⚡ Fun fact: i have a 2:1 Bsc Biochemistry degree...

<!---
omargamer-99/omargamer-99 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
